
//------------------------------------------------------------------------------
// 
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// 
//------------------------------------------------------------------------------

// Generated from: ProtoBuff/ltlmopMsg.proto
namespace LTLMoPCsharpInterface
{
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PythonRequestMsg")]
    public partial class PythonRequestMsg : global::ProtoBuf.IExtensible
    {
      public PythonRequestMsg() {}
      
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }

    private LTLMoPCsharpInterface.PythonRequestMsg.Velocity _vel = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"vel", DataFormat = global::ProtoBuf.DataFormat.Default)][global::System.ComponentModel.DefaultValue(null)]
    public LTLMoPCsharpInterface.PythonRequestMsg.Velocity vel
    {
      get { return _vel; }
      set { _vel = value; }
    }

    private LTLMoPCsharpInterface.PythonRequestMsg.Actuator _actuator = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"actuator", DataFormat = global::ProtoBuf.DataFormat.Default)][global::System.ComponentModel.DefaultValue(null)]
    public LTLMoPCsharpInterface.PythonRequestMsg.Actuator actuator
    {
      get { return _actuator; }
      set { _actuator = value; }
    }

    private LTLMoPCsharpInterface.PythonRequestMsg.SensorType _sensor = LTLMoPCsharpInterface.PythonRequestMsg.SensorType.LIDAR;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"sensor", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)][global::System.ComponentModel.DefaultValue(LTLMoPCsharpInterface.PythonRequestMsg.SensorType.LIDAR)]
    public LTLMoPCsharpInterface.PythonRequestMsg.SensorType sensor
    {
      get { return _sensor; }
      set { _sensor = value; }
    }

    private LTLMoPCsharpInterface.PythonRequestMsg.ActuatorType _actuatorType = LTLMoPCsharpInterface.PythonRequestMsg.ActuatorType.ARM;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"actuatorType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)][global::System.ComponentModel.DefaultValue(LTLMoPCsharpInterface.PythonRequestMsg.ActuatorType.ARM)]
    public LTLMoPCsharpInterface.PythonRequestMsg.ActuatorType actuatorType
    {
      get { return _actuatorType; }
      set { _actuatorType = value; }
    }
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Velocity")]
    public partial class Velocity : global::ProtoBuf.IExtensible
    {
      public Velocity() {}
      

    private double _v = default(double);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"v", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)][global::System.ComponentModel.DefaultValue(default(double))]
    public double v
    {
      get { return _v; }
      set { _v = value; }
    }

    private double _omega = default(double);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"omega", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)][global::System.ComponentModel.DefaultValue(default(double))]
    public double omega
    {
      get { return _omega; }
      set { _omega = value; }
    }
      private global::ProtoBuf.IExtension extensionObject;
      global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }
  
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Actuator")]
    public partial class Actuator : global::ProtoBuf.IExtensible
    {
      public Actuator() {}
      

    private double _status = default(double);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)][global::System.ComponentModel.DefaultValue(default(double))]
    public double status
    {
      get { return _status; }
      set { _status = value; }
    }
      private global::ProtoBuf.IExtension extensionObject;
      global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }
  
    public enum SensorType
    {
      LIDAR = 0,
    ARTAG = 1
    }
  
    public enum ActuatorType
    {
      ARM = 0
    }
  
      private global::ProtoBuf.IExtension extensionObject;
      global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }
  
}