# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2


_INITMESSAGE_SENSORTYPE = descriptor.EnumDescriptor(
  name='SensorType',
  full_name='LTLMoP_Csharp.InitMessage.SensorType',
  filename='SensorType',
  values=[
    descriptor.EnumValueDescriptor(
      name='LIDAR', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ARTAG', index=1, number=1,
      options=None,
      type=None),
  ],
  options=None,
)

_INITMESSAGE_ACTUATORTYPE = descriptor.EnumDescriptor(
  name='ActuatorType',
  full_name='LTLMoP_Csharp.InitMessage.ActuatorType',
  filename='ActuatorType',
  values=[
    descriptor.EnumValueDescriptor(
      name='ARM', index=0, number=0,
      options=None,
      type=None),
  ],
  options=None,
)


_INITMESSAGE = descriptor.Descriptor(
  name='InitMessage',
  full_name='LTLMoP_Csharp.InitMessage',
  filename='ltlmopMsg.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='LTLMoP_Csharp.InitMessage.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='sensor', full_name='LTLMoP_Csharp.InitMessage.sensor', index=1,
      number=2, type=14, cpp_type=8, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='actuator', full_name='LTLMoP_Csharp.InitMessage.actuator', index=2,
      number=3, type=14, cpp_type=8, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
    _INITMESSAGE_SENSORTYPE,
    _INITMESSAGE_ACTUATORTYPE,
  ],
  options=None)


_INITMESSAGE.fields_by_name['sensor'].enum_type = _INITMESSAGE_SENSORTYPE
_INITMESSAGE.fields_by_name['actuator'].enum_type = _INITMESSAGE_ACTUATORTYPE

class InitMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INITMESSAGE

